//<#!@READ-ONLY-SECTION-START@!#>
/*
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of simpleDwemoApp generated by C++ Generator for SystemC/TLM2
 */

#include "cfm_simpledwemoapp_top.h"
using namespace std;
using namespace sc_core;
using namespace cf_dt;
using namespace cf_pk;
using namespace cf_core;

#ifdef COFS_MODEL_TYPE_APPLICATION_MODELING
int sc_main(int argc, char *argv[])
{

	// simpleDwemoApp pre-simulation section
	cfm_simpledwemoapp_cb_pre_simulation();

	// simpleDwemoApp instantiation
	cfm_simpledwemoapp* cfmi_simpleDwemoApp = new cfm_simpledwemoapp("simpleDwemoApp");

	// start simulation
	cf_start();

	// shutdown simulator
	cf_stop();
	delete cfmi_simpleDwemoApp;

	return EXIT_SUCCESS;
}
#endif // COFS_MODEL_TYPE_APPLICATION_MODELING

//<#!@READ-ONLY-SECTION-END@!#>