//<#!@READ-ONLY-SECTION-START@!#>
/*
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of simpleDwemoApp generated by C++ Generator for SystemC/TLM2
 */

#include "cfm_simpledwemoapp_user.h"
using namespace std;
using namespace sc_core;
using namespace cf_dt;
using namespace cf_pk;
using namespace cf_core;

void cfm_simpledwemoapp_cb_pre_simulation(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'simpleDwemoApp pre simulation' algorithm generated code

	//End of 'simpleDwemoApp pre simulation' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}

//<#!@READ-ONLY-SECTION-END@!#>