//<#!@READ-ONLY-SECTION-START@!#>
/*
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of simpleDwemoApp generated by C++ Generator for SystemC/TLM2
 */

#include "cfm_simpledwemoapp_global.h"
using namespace std;
using namespace sc_core;
using namespace cf_dt;
using namespace cf_pk;
using namespace cf_core;

/// \name Global definitions
//@{
///		\addtogroup dxgGlobals 
//@{
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'simpleDwemoApp global definitions' algorithm generated code

//End of 'simpleDwemoApp global definitions' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>
//@}
//@}

//<#!@READ-ONLY-SECTION-END@!#>