//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of simpleGitDemoApp generated by C++ Generator for SystemC/TLM2
 */
#ifndef COFS_MODEL_SIMPLEGITDEMOAPP_TOP_MODEL
#define COFS_MODEL_SIMPLEGITDEMOAPP_TOP_MODEL

#include "cfm_simplegitdemoapp_user.h"
#include "cfm_simplegitdemoapp.h"

#endif // COFS_MODEL_SIMPLEGITDEMOAPP_TOP_MODEL

//<#!@READ-ONLY-SECTION-END@!#>