//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_simplegitdemoapp
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of simpleGitDemoApp generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_SIMPLEGITDEMOAPP
#define COFS_MODEL_SIMPLEGITDEMOAPP

#include "cfm_simplegitdemoapp_global.h"
#include "cfm_simplegitdemoapp_global_types.h"
#include "cofluent.h"

#include "cfm_consumer.h"
#include "cfm_processingfunction.h"
#include "cfm_producer.h"

//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'simpleGitDemoApp includes' algorithm generated code

//End of 'simpleGitDemoApp includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>

///    \defgroup dxgsimpleGitDemoApp Function simpleGitDemoApp
//@{
///        \page dxpsimpleGitDemoApp
//@{
///    \brief simpleGitDemoApp function model.
class cfm_simplegitdemoapp: public cf_core::cf_application {
public:
	/// relations typedef
	typedef cf_core::cf_message_queue<cf_core::cf_payload_int> mq_MsgQ_t;
	typedef cf_core::cf_message_queue<cf_core::cf_payload_int> mq_MsgQ2_t;

	/// constructor
	cfm_simplegitdemoapp(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_simplegitdemoapp(void);
	virtual void cb_before_elaboration(void);

	void cb_end_of_elaboration(void);
	void cb_end_of_simulation(void);

public:
	/// \name functions
	//@{
	cfm_consumer* Consumer;
	cfm_processingfunction* ProcessingFunction;
	cfm_producer* Producer;
	//@}

protected:
	/// initialize attributes
	void cb_init_attributes(void);
	/// initialize definitions
	void cb_init_local_vars(void);

public:
	/// \name relations
	//@{
	mq_MsgQ_t mq_MsgQ;
	mq_MsgQ2_t mq_MsgQ2;
	//@}

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'simpleGitDemoApp local declarations' algorithm generated code

	//End of 'simpleGitDemoApp local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};

//@}
//@}
#endif // COFS_MODEL_SIMPLEGITDEMOAPP

//<#!@READ-ONLY-SECTION-END@!#>