//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_processingfunction
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of simpleGitDemoApp generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_SIMPLEGITDEMOAPP_PROCESSINGFUNCTION
#define COFS_MODEL_SIMPLEGITDEMOAPP_PROCESSINGFUNCTION

#include "cfm_simplegitdemoapp_global.h"
#include "cfm_simplegitdemoapp_global_types.h"
#include "cofluent.h"

//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'ProcessingFunction includes' algorithm generated code

//End of 'ProcessingFunction includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>

///    \defgroup dxgProcessingFunction Function ProcessingFunction
//@{
///        \page dxpProcessingFunction
//@{
///    \brief ProcessingFunction function model.
class cfm_processingfunction: public cf_core::cf_function {
public:
	SC_HAS_PROCESS (cfm_processingfunction);

	/// ports typedef
	typedef cf_core::cf_mq_initiator_socket<cfm_processingfunction,
			cf_core::cf_payload_int> p_mq_MsgQ_t;
	typedef cf_core::cf_mq_initiator_socket<cfm_processingfunction,
			cf_core::cf_payload_int> p_mq_MsgQ2_t;

	/// constructor
	cfm_processingfunction(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_processingfunction(void);
	virtual void cb_before_elaboration(void);
	virtual void cb_end_of_simulation(void);

public:
	/// \name input/output ports
	//@{
	p_mq_MsgQ_t p_mq_MsgQ;
	p_mq_MsgQ2_t p_mq_MsgQ2;
	//@}

protected:
	/// initialize attributes
	void cb_init_attributes(void);
	/// initialize definitions
	void cb_init_local_vars(void);

	/// behavior
	void cfm_behavior();
	/// init operation
	void cfm_op_init();
	/// process operation
	void cfm_op_process();

protected:
	/// \name operations
	//@{
	cf_core::cf_operation init;
	cf_core::cf_operation process;
	//@}

private:
	/// \name input/output local buffers
	//@{
	int MsgQ;
	cf_core::cf_payload_int MsgQ_trans;
	int MsgQ2;
	cf_core::cf_payload_int MsgQ2_trans;
	//@}

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'ProcessingFunction local declarations' algorithm generated code

	//End of 'ProcessingFunction local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};

//@}
//@}
#endif // COFS_MODEL_SIMPLEGITDEMOAPP_PROCESSINGFUNCTION

//<#!@READ-ONLY-SECTION-END@!#>