//<#!@READ-ONLY-SECTION-START@!#>
/// \mainpage simpleGitDemoApp
///
/// Source code generated by Intel CoFluent C++ Generator for SystemC/TLM2 for:
///
/// project: simpleGitDemoApp
///
/// \section dxsGlobals Globals
///
///    - \subpage dxpGlobals "Global declarations/initializations"
///
///    - \subpage dxpRelTypes "Relation Datatypes"
///
///    - \subpage dxpDPTypes "Design Parameter Types"
///
///    - \subpage dxpUserCallbacks "User-defined callback functions"
///
/// \section dxsModules Design modules
///
///    - \subpage dxpsimpleGitDemoApp "Application simpleGitDemoApp"
///
///    - \subpage dxpsimpleGitDemoApp "Function simpleGitDemoApp"
///
///    - \subpage dxpProducer "Function Producer"
///
///    - \subpage dxpConsumer "Function Consumer"
///
///    - \subpage dxpProcessingFunction "Function ProcessingFunction"
///
///
/// Intel(R) CoFluent(TM) Studio - Intel Corporation
/// Version: 8.1.0 r1_nolic - Build id: 52-52
/// C++ Modeling Library for SystemC/TLM2 (SCL)
///

#ifndef COFS_MODEL_SIMPLEGITDEMOAPP_GLOBAL_DEFINITIONS
#define COFS_MODEL_SIMPLEGITDEMOAPP_GLOBAL_DEFINITIONS

#include "cfm_simplegitdemoapp_global_types.h"
#include "cofluent.h"

#ifndef COFS_MODEL_APPLICATION_LEVEL
#define COFS_MODEL_APPLICATION_LEVEL
#endif

/// \defgroup dxgGlobals global declarations
//@{
///		\page dxpGlobals
//@{
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'simpleGitDemoApp global declarations' algorithm generated code

//End of 'simpleGitDemoApp global declarations' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>
//@}
//@}

#endif // COFS_MODEL_SIMPLEGITDEMOAPP_GLOBAL_DEFINITIONS

//<#!@READ-ONLY-SECTION-END@!#>