//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_sampledemoapp
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of sampleDemoApp generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_SAMPLEDEMOAPP
#define COFS_MODEL_SAMPLEDEMOAPP

#include "cfm_sampledemoapp_global.h"
#include "cfm_sampledemoapp_global_types.h"
#include "cofluent.h"

#include "cfm_consumer.h"
#include "cfm_producer.h"

//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'sampleDemoApp includes' algorithm generated code

//End of 'sampleDemoApp includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>

///    \defgroup dxgsampleDemoApp Function sampleDemoApp
//@{
///        \page dxpsampleDemoApp
//@{
///    \brief sampleDemoApp function model.
class cfm_sampledemoapp: public cf_core::cf_application {
public:
	/// relations typedef
	typedef cf_core::cf_message_queue<cf_core::cf_payload_int> mq_MsgQ_t;

	/// constructor
	cfm_sampledemoapp(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_sampledemoapp(void);
	virtual void cb_before_elaboration(void);

	void cb_end_of_elaboration(void);
	void cb_end_of_simulation(void);

public:
	/// \name functions
	//@{
	cfm_consumer* Consumer;
	cfm_producer* Producer;
	//@}

protected:
	/// initialize attributes
	void cb_init_attributes(void);
	/// initialize definitions
	void cb_init_local_vars(void);

public:
	/// \name relations
	//@{
	mq_MsgQ_t mq_MsgQ;
	//@}

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'sampleDemoApp local declarations' algorithm generated code

	//End of 'sampleDemoApp local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};

//@}
//@}
#endif // COFS_MODEL_SAMPLEDEMOAPP

//<#!@READ-ONLY-SECTION-END@!#>