//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of sampleDemoApp generated by C++ Generator for SystemC/TLM2
 */
#ifndef COFS_MODEL_SAMPLEDEMOAPP_TOP_MODEL
#define COFS_MODEL_SAMPLEDEMOAPP_TOP_MODEL

#include "cfm_sampledemoapp_user.h"
#include "cfm_sampledemoapp.h"

#endif // COFS_MODEL_SAMPLEDEMOAPP_TOP_MODEL

//<#!@READ-ONLY-SECTION-END@!#>