//<#!@READ-ONLY-SECTION-START@!#>
/*
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of sampleDemoApp generated by C++ Generator for SystemC/TLM2
 */

#include "cfm_sampledemoapp_top.h"
using namespace std;
using namespace sc_core;
using namespace cf_dt;
using namespace cf_pk;
using namespace cf_core;

#ifdef COFS_MODEL_TYPE_APPLICATION_MODELING
int sc_main(int argc, char *argv[])
{

	// sampleDemoApp pre-simulation section
	cfm_sampledemoapp_cb_pre_simulation();

	// sampleDemoApp instantiation
	cfm_sampledemoapp* cfmi_sampleDemoApp = new cfm_sampledemoapp("sampleDemoApp");

	// start simulation
	cf_start();

	// shutdown simulator
	cf_stop();
	delete cfmi_sampleDemoApp;

	return EXIT_SUCCESS;
}
#endif // COFS_MODEL_TYPE_APPLICATION_MODELING

//<#!@READ-ONLY-SECTION-END@!#>