//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of simpleDwemoApp generated by C++ Generator for SystemC/TLM2
 */
#ifndef COFS_MODEL_SIMPLEDWEMOAPP_TOP_MODEL
#define COFS_MODEL_SIMPLEDWEMOAPP_TOP_MODEL

#include "cfm_simpledwemoapp_user.h"
#include "cfm_simpledwemoapp.h"

#endif // COFS_MODEL_SIMPLEDWEMOAPP_TOP_MODEL

//<#!@READ-ONLY-SECTION-END@!#>